apiVersion: v2
name: connect
version: 1.12.2
description: A Helm chart for deploying 1Password Connect and the 1Password Connect Kubernetes Operator
keywords:
  - "1Password"
  - "1Password Connect"
  - "1Password Operator"
home: https://1password.com/secrets/
maintainers:
  - name: 1Password Secrets Integrations Team
    email: support+business@1password.com
icon: https://avatars.githubusercontent.com/u/38230737
appVersion: "1.7.1"
