{{- if eq (tpl (.Values.connect.serviceAccount.create | toString) .) "true" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.connect.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "onepassword-connect.labels" . | nindent 4 }}
  {{- with .Values.connect.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
