apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.connect.applicationName }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.connect.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/component: connect
    {{- include "onepassword-connect.labels" . | nindent 4 }}
spec:
  type: {{ .Values.connect.serviceType }}
  selector:
    app: {{ .Values.connect.applicationName }}
  ports:
    - port: {{ .Values.connect.sync.httpPort }}
      name: {{ .Values.connect.sync.name }}
    {{- if .Values.connect.tls.enabled }}
    - port: {{ .Values.connect.api.httpsPort }}
      name: {{ .Values.connect.api.name }}-https
    {{- else }}
    - port: {{ .Values.connect.api.httpPort }}
      name: {{ .Values.connect.api.name }}
    {{- end }}
