apiVersion: v2
name: kuberenetes-secrets-injector
description: A Helm chart for deploying 1Password Kuberenetes Sercrets Injector
type: application
home: https://1password.com/secrets/
keywords:
  - "1Password"
  - "1Password Secrets Injector"
  - "1Password Kubernetes Secrets Injector"
  - "Secrets Injector"
maintainers:
  - name: 1Password Secrets Integrations Team
    email: support+business@1password.com
icon: https://avatars.githubusercontent.com/u/38230737
appVersion: 1.0.0
version: 1.0.0
